404: Not Found
components:
  examples:
    AppUserSchemaResponse:
      value:
        properties:
          profile:
            type: object
    GroupSchemaResponse:
      value:
        properties:
          profile:
            type: object
    UserSchemaResponse:
      value:
        properties:
          profile:
            type: object
